export const PERMISSIONS = {
  // User management
  USER_CREATE: 'USER_CREATE',
  USER_READ: 'USER_READ',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',

  // Role management
  ROLE_ASSIGN: 'ROLE_ASSIGN',

  // Student management
  STUDENT_CREATE: 'STUDENT_CREATE',
  STUDENT_READ: 'STUDENT_READ',
  STUDENT_UPDATE: 'STUDENT_UPDATE',
  STUDENT_DELETE: 'STUDENT_DELETE',

  // Teacher management
  TEACHER_CREATE: 'TEACHER_CREATE',
  TEACHER_READ: 'TEACHER_READ',
  TEACHER_UPDATE: 'TEACHER_UPDATE',
  TEACHER_DELETE: 'TEACHER_DELETE',

  // Parent management
  PARENT_CREATE: 'PARENT_CREATE',
  PARENT_READ: 'PARENT_READ',
  PARENT_UPDATE: 'PARENT_UPDATE',
  PARENT_DELETE: 'PARENT_DELETE',

  // Class management
  CLASS_CREATE: 'CLASS_CREATE',
  CLASS_READ: 'CLASS_READ',
  CLASS_UPDATE: 'CLASS_UPDATE',
  CLASS_DELETE: 'CLASS_DELETE',

  // Subject management
  SUBJECT_CREATE: 'SUBJECT_CREATE',
  SUBJECT_READ: 'SUBJECT_READ',
  SUBJECT_UPDATE: 'SUBJECT_UPDATE',
  SUBJECT_DELETE: 'SUBJECT_DELETE',

  // Attendance
  ATTENDANCE_CREATE: 'ATTENDANCE_CREATE',
  ATTENDANCE_READ: 'ATTENDANCE_READ',
  ATTENDANCE_UPDATE: 'ATTENDANCE_UPDATE',
  ATTENDANCE_DELETE: 'ATTENDANCE_DELETE',

  // Grades
  GRADE_CREATE: 'GRADE_CREATE',
  GRADE_READ: 'GRADE_READ',
  GRADE_UPDATE: 'GRADE_UPDATE',
  GRADE_DELETE: 'GRADE_DELETE',

  // Notes
  NOTE_CREATE: 'NOTE_CREATE',
  NOTE_READ: 'NOTE_READ',
  NOTE_UPDATE: 'NOTE_UPDATE',
  NOTE_DELETE: 'NOTE_DELETE',

  // Reports
  REPORT_READ: 'REPORT_READ',

  // Audit
  AUDIT_READ: 'AUDIT_READ',

  // Synchronization
  SYNC_MANAGE: 'SYNC_MANAGE'
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const checkPermission = (userPermissions: Permission[], requiredPermission: Permission) => {
  return userPermissions.includes(requiredPermission);
};
